In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

In [4]:
#python is dynamically typed language
x = 3
x = "three"

In [5]:
print(x)

three


In [6]:
#heterogeneous lists in Python
L = [True, '2', 1, 4.3]
[type(item) for item in L] #each item is a complete python object, with type info, reference count

[bool, str, int, float]

In [7]:
# Numpy array - fixed type lists (more efficient in storing and manipulating lists, continuous block of data)

array = np.array([1,3,5,7], dtype='int')
array_nested = np.array([range(i, i+3) for i in [1,3,5]])
array_nested

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [11]:
#creating specific arrays
np.zeros
np.ones((3,2))
np.random.random((3,3))
np.eye(4) # identity matrix


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

NumPy Array Attributes

In [46]:
np.random.seed(5)
x3 = np.random.randint(10, size=(3,3,5)) #three dimentional array

print('Data type of the array is',x3.dtype)
x3[1,1,3] = 100 #modifying elements

x3[1, ::-1,::-1] #reverse array
x3[1, :, 3]
x3[1, 0] # row access



Data type of the array is int32


array([1, 4, 6, 2, 9])

In [53]:
# array slices return views rather than copies of array data
x3 = np.random.randint(10, size=(3,3,5))
x3_sub = x3[1, 0]
print(x3_sub)
x3_sub[1] = 100
x3
#copy array instead of view
x3_sub_copy = x3[1, 0].copy()
print(x3_sub)
x3_sub_copy[1] = 100
x3

[6 9 2 9 3]
[  6 100   2   9   3]


array([[[  4,   1,   6,   3,   4],
        [  3,   1,   4,   2,   3],
        [  4,   9,   4,   0,   6]],

       [[  6, 100,   2,   9,   3],
        [  0,   8,   8,   9,   7],
        [  4,   8,   6,   8,   0]],

       [[  5,   3,   4,   0,   2],
        [  2,   1,   1,   7,   1],
        [  7,   2,   6,   3,   6]]])

In [60]:
#reshaping
grid = np.arange(1,10).reshape((3,3))
print(grid)
grid = grid.reshape((9,1))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
